version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  console:
    container_name: console
    image: console:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.console.rule=Host(`console.deploy.nohaxito.xyz`)
      - traefik.http.routers.console.tls=true
      - traefik.http.routers.console.tls.certresolver=lets-encrypt
    networks:
      - internal
      - web
    restart: always
