import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import { ProgressBarProvider } from "@/components/providers/progressbar-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 5;
export const dynamic = "force-dynamic";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("relative", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ProgressBarProvider>
            <div className="relative flex min-h-screen flex-col dark:bg-neutral-950">
              <div className="container mx-auto relative flex-1 py-4">
                <div className="absolute top-4 right-4">
                  <ModeToggle />
                </div>
                {children}
              </div>
            </div>
            <Toaster />
          </ProgressBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
